#!/usr/bin/env python

Import('env')
Import("env_modules")

env_tts = env.Clone()

env_tts.Prepend (CPPPATH = [ './flite' ])
env_tts.Prepend (CPPDEFINES = [ '-DCST_NO_SOCKETS' ])

env_tts.add_source_files(env.modules_sources, "./flite_src/**/**/*.c")

if env["platform"] in ["windows"]:
	env_tts.add_source_files(env.modules_sources, "./flite_src/audio/windows/*.c")
	env_tts.add_source_files(env.modules_sources, "./flite_src/utils/windows/*.c")

if env["platform"] in ["x11"]:
	env_tts.add_source_files(env.modules_sources, "./flite_src/audio/linux/*.c")
	env_tts.add_source_files(env.modules_sources, "./flite_src/utils/linux/*.c")


env_tts.add_source_files(env.modules_sources, "*.cpp")

if not env.msvc:
	if env["platform"] in ["windows"]:
		env.Append(LIBS=['winmm'])